### ISSUE TITLE
How to Add RegistredTime (TimePicker  control) to the Customers Table items, 

### ISSUE THREAD

**Issue by red2014** [Microsoft/InventorySample#41]
Can I have help from you .
I need to add a TimePicker to the form as FormTimePicker to display RegistredTime colomn in Customers table
As Example:
<controls:FormTimePicker  Header="Registred Time" Time="{x:Bind EditableItem.RegistredTime , Mode=TwoWay}" />
I  create FormTimePicker.xaml   in Control folder. 
I  create class FormTimePicker.cs in Form folder.
BUT NO CHANCE .
GET exception  :
System.NullReferenceException: Object reference not set to an instance of an object.
   at Inventory.Controls.FormTimePicker.UpdateVisualState()
   at Inventory.Controls.FormTimePicker.OnApplyTemplate()
   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
   at Inventory.Controls.FluidGrid.MeasureOverride(Size availableSize)

Thanks

**Comment by fmassicci** [comment]
I have the same problem with CheckBox

**Comment by rangiesrule** [comment]
> I have the same problem with CheckBox

@fmassicci did find the cause in your case?

**Comment by fmassicci** [comment]
Yes, We have created a compatible control.

Da: rangiesrule <notifications@github.com>
Inviato: mercoledì 20 marzo 2019 04:38
A: Microsoft/InventorySample <InventorySample@noreply.github.com>
Cc: Fabio <fmassicci@msn.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [Microsoft/InventorySample] How to Add RegistredTime (TimePicker control) to the Customers Table items, (#41)


I have the same problem with CheckBox

@fmassicci<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffmassicci&data=02%7C01%7C%7C5917bc8e550a46ef452008d6ace57d02%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636886498969335065&sdata=5mVqwb%2B63%2BrUsgG0S5C2QTN56ghbCUtqi%2F%2Bi7VqAy7Y%3D&reserved=0> did find the cause in your case?
